import Layout from "@/Components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/1222.png";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="profilepic"
                className="w-[85%] h-auto"
              />
            </div>
            <div className="w-1/2">
              <h1>
                Passionate Deep Learning Enthusiast and Software Developer{" "}
              </h1>
              <p>
                Aspiring software developer with a strong foundation in
                programming and a passion for creating innovative solutions.
                Strong analytical and problem-solving skills, with a keen
                attention to detail. Able to work effectively in a team-oriented
                environment, collaborating with colleagues to deliver
                high-quality code
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
